### ISSUE TITLE
Distutils not found

### ISSUE THREAD

**Issue by gwm17** [styfenschaer/rocket-fft#11]
I recently upgraded to python 3.12 and with the latest install of rocket-fft (0.2.4) and numba (0.59.0) I get the following error upon running one of my test scripts:

UserWarning: Numba extension module 'rocket_fft' failed to load due to 'ModuleNotFoundError(No module named 'distutils')'.

Looks like it is still trying to find distutils. I'm using MacOS 14.4, python 3.12.2. I've been able to reproduce this in a clean environment by launching the interpreter and just importing both numba and rocket-fft.

Please let me know if you need any more details! Rocket-fft is awesome and has been really helpful for working on large datasets!

**Comment by gwm17** [comment]
Awesome thank you!

**Comment by styfenschaer** [comment]
Hi @gwm17 

Just wanted to let you know that a new version is now available on PyPI.

**Comment by gwm17** [comment]
Excellent! Everything looks like its working now. Thanks @styfenschaer!
