### ISSUE TITLE
compatibility issue with numpy version > 1.25

### ISSUE THREAD

**Issue by EliousMondal** [styfenschaer/rocket-fft#4]
Thanks a lot for making this. I am incorporated this in my code and it works really good. But I have a small issue for now. I tried to install rocket-fft and realised that I need numpy version ~ 1.21 because of which I have to uninstall my numpy and install a lower version to make the rocket-fft and some lower version of other packages like scipy, mpi4py, matplotlib. Is there a newer version of rocket-fft which is compatible with higher versions of numpy? or am I installing it wrong (I just did 'pip install rocket-fft')?

**Comment by styfenschaer** [comment]
Hi @EliousMondal 

I am glad that you find it helpful.
 
Rocket-FFT does not have any requirements for the Numpy version. However, Numba, which is one of the strict requirements for Rocket-FFT, does. E.g. Numba 0.57 requires at least Numpy 1.21 and the maximum supported version is (if I remember correctly) 1.24. If you need Numpy >1.25, you can check if the release candidate of [Numba 0.58](https://numba.discourse.group/t/ann-numba-0-58-0rc1-and-llvmlite-0-41-0rc1/2078) works for you, which supports up to and including Numpy 1.26.

If you still think that the problems originate from Rocket-FFT, please let me know and share the corresponding error message.

**Comment by EliousMondal** [comment]
I no longer have a problem with Rocket-FFT. Thanks again for the package.
